#! /bin/sh

sxhkd &
panel &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d Web Term Edit Music Thunar

#bspc rule -a thunar desktop=^4 state=floating follow=on
#bspc rule -a google-chrome-stable desktop=^1
#bspc rule -a vlc state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
